# JVM performance (IMPORTANT)
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8

# Speed + stability
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.configuration-cache=false

# AndroidX
android.useAndroidX=true

# Architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# React Native features
newArchEnabled=true
hermesEnabled=true

org.gradle.workers.max=2